# Generated by Django 2.0 on 2018-01-07 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('no', 'No'), ('busy', 'Busy'), ('yes', 'Yes')], default='no', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('primary', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('calendars_retrieved_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='IcalCalendar',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_retrieved_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_calendars', to='calendars.GoogleUser')),
            ],
        ),
        migrations.CreateModel(
            name='MergedCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_calendars', to='calendars.GoogleUser')),
            ],
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_calendars', to='calendars.GoogleUser'),
        ),
        migrations.AddField(
            model_name='calendaraccess',
            name='g_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='calendars.GoogleCalendar'),
        ),
        migrations.AddField(
            model_name='calendaraccess',
            name='i_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='calendars.IcalCalendar'),
        ),
        migrations.AddField(
            model_name='calendaraccess',
            name='mergedCalendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='calendars.MergedCalendar'),
        ),
    ]
