# Generated by Django 2.0 on 2018-01-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20180101_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='refresh_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
