# Generated by Django 2.1.7 on 2019-02-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_add_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalcalendar',
            name='person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
