# Generated by Django 2.2.13 on 2020-06-28 22:00

from django.db import migrations, models

import calendars.models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0003_icalcalendar_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="icalcalendar",
            name="icalType",
            field=models.CharField(
                choices=[
                    (calendars.models.IcalType("Generic"), "Generic"),
                    (calendars.models.IcalType("WhosOff"), "WhosOff"),
                    (calendars.models.IcalType("BambooHR"), "BambooHR"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
