# Generated by Django 2.0 on 2018-01-01 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_googleuser_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('primary', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='googleuser',
            name='calendars_retrieved_at',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='user',
            field=models.ForeignKey(on_delete='cascade', to='calendars.GoogleUser'),
        ),
    ]
