# Generated by Django 2.2.13 on 2020-06-28 22:01

from django.db import migrations
from enum import Enum

class IcalType(Enum):
    GENERIC = "Generic"
    WHOSOFF = "WhosOff"

def gen_icalType(apps, schema_editor):
    IcalCalendar = apps.get_model('calendars', 'IcalCalendar')
    for row in IcalCalendar.objects.all():
        if row.person == None:
            row.icalType = IcalType.GENERIC
        else:
            row.icalType = IcalType.WHOSOFF
        row.save(update_fields=['icalType'])


class Migration(migrations.Migration):
    dependencies = [
        ('calendars', '0004_icalcalendar_icaltype'),
    ]

    operations = [
        migrations.RunPython(gen_icalType, reverse_code=migrations.RunPython.noop),
    ]
