# Generated by Django 2.2.13 on 2020-06-28 22:01

from enum import Enum

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


class IcalType(Enum):
    GENERIC = "Generic"
    WHOSOFF = "WhosOff"


def gen_icalType(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    IcalCalendar = apps.get_model("calendars", "IcalCalendar")
    for row in IcalCalendar.objects.all():
        if row.person is None:
            row.icalType = str(IcalType.GENERIC)
        else:
            row.icalType = str(IcalType.WHOSOFF)
        row.save(update_fields=["icalType"])


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0004_icalcalendar_icaltype"),
    ]

    operations = [
        migrations.RunPython(gen_icalType, reverse_code=migrations.RunPython.noop),
    ]
